### PR TITLE
Fix opener electronic strike actuation in HA

### LINKED ISSUE #485: Nuki Opener ACL configuration mismatch for "open"
### PROBLEM DESCRIPTION

Nuki **Opener** won't show the `open` action in Home Assistant if Nuki **SmartLock** does not have the `unlatch` action enabled.

https://github.com/technyon/nuki_hub/blob/fed5f95490bee8a57c5ef3467d2cf79e4e099616/src/NukiNetwork.cpp#L883

At the moment I am using only the **Opener**, so having disabled the **SmartLock** I was not able to see the action to open.

### REQUESTED INFORMATION

- [x] Read the [Contributing Guide and Policy](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/technyon/nuki_hub/blob/master/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/technyon/nuki_hub/issues)
- [x] Searched the problem in [discussions](https://github.com/technyon/nuki_hub/discussions)
- [x] Searched the problem in the [docs](https://github.com/technyon/nuki_hub)
- [x] Searched the problem in the [chat](https://discord.gg/9nPq85bP4p)
- [x] Device used (e.g., ESP32-S3): ESP-32
- [x] Nuki Hub binary firmware version number used: 9.01
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Provide the output of http://nukihubIP/info:
```
Version: 9.01
Build: 10981972651.1432.1
```

### TO REPRODUCE

1. Disable Nuki Smartlock
2. Enable ACL Nuki Opener Access Control > Electric Strike Actuation

❌ Home Assitant won't show the Open button

1. Enable Nuki Smartlock
2. Enable ACL Nuki Lock Access Control > Unlatch

✅  Home Assistant shows the Open button

### EXPECTED BEHAVIOUR

- Electric Strike Actuation should show the Open button.

### SCREENSHOTS
N/A

### ADDITIONAL CONTEXT
N/A

### PR DESCRIPTION
**Pull request by iranl**
## Description:

**Related issue (if applicable):** fixes #485 

## Checklist:
  - [x] The pull request is done against the latest master branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works
  - [x] I accept the [CLA](https://github.com/technyon/nuki_hub/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

File: src/NukiNetwork.cpp [hunk 1]
```diff
@@ -880,7 +880,11 @@ void NukiNetwork::publishHASSConfig(char* deviceType, const char* baseTopic, cha
 
     uint32_t aclPrefs[17];
     _preferences->getBytes(preference_acl, &aclPrefs, sizeof(aclPrefs));
-    if((int)aclPrefs[2]) json["pl_open"] = openAction;
+
+`   if((strcmp(deviceType, "SmartLock") != 0 && (int)aclPrefs[2]) || (strcmp(deviceType, "SmartLock") == 0 && (int)aclPrefs[11]))
```
Comment (duhow) [inline src/NukiNetwork.cpp:884]:
```suggestion
    if((strcmp(deviceType, "SmartLock") != 0 && (int)aclPrefs[2]) || (strcmp(deviceType, "SmartLock") == 0 && (int)aclPrefs[11]))
```
